### ISSUE TITLE
CI: experiment with armv7h builds

### ISSUE THREAD

**Issue by petrbel** [iterait/dockerfiles#38]

**Comment by FloopCZ** [comment]
Not really sure how at this moment. Sorry.

**Comment by petrbel** [comment]
there's an interesting discussion with some code snippets here... Maybe it will work (qemu seems to work in circlci) https://ideas.circleci.com/ideas/CCI-I-900

**Comment by FloopCZ** [comment]
Unfortunately, they talk about Docker, but we need machine instance because of `--squash`. But maybe we could run `qemu` in VM of the machine instance! :-D
